### ISSUE TITLE
failed compilation with hand-compiled libprotobuf.so(2.6.1)

### ISSUE THREAD

**Issue by peyer** [OAID/Tengine#27]
@HEGALLIS I have tried to compiled protobuf(2.6.1) and put the path  libprotobuf.so  to android_build_armv8.sh, while when Linking lintengine.so, the compilation info shown that generated_message_reflection.h:496: undefined reference to `typeinfo for google::protobuf::Message'

the te_caffe.pb.cc file was generated by host protoc(x86_64),

**Comment by cyberfire** [comment]
@peyer 

Is the version of protoc in your x86_64 is 2.61  too? 
Also, besides libprotobuf.so, please overwrite the headers files too.

Thanks,

Haitao

**Comment by lyuchuny3** [comment]
try to build with protobuf 3.0

**Comment by peyer** [comment]
@cyberfire @lyuchuny3 @HEGALLIS . Sorry about reply you so late. I have successfully compiled protobuf 3.0 on x86_64 and ARM. And I changed Makefile to compile Tengine on x86_64 to transform caffemodel to tengine format on host, it worked now. Thanks again!
